unit drawgbr;
interface
uses vectorD,complex2,draw;
type
Tgerlayer = record
 f,f2 : text;
 diams : array of integer;
 end;
 Tgerber = object(Tdraw)
  GL : array[0..3] of Tgerlayer;
  offx,offy : double;
  constructor create(filename : string);
  procedure poly(n : integer;v : cvec;nm : string); virtual;
  procedure hole(r : tc;diam : double;nm : string); virtual;
//  procedure via(r : tc;diam,diamp : double;nm : string); virtual;
//  procedure arc(r0 : tc;r,th1,th2 : double;nm : string); virtual;
//  procedure arc2(var r1,d : tc;r,th,w,dir : double;nm : string); virtual;
  procedure circle(r0 : tc;r : double;nm : string); virtual;
//  Procedure rect(r0,r1 : tc;w : double;nm : string); virtual;
//  procedure lable(r0,dir : tc;s,nm : string); virtual;
  procedure closedrw; virtual;
  procedure show; virtual;
  end;
 Pgerber=^Tgerber;

 
implementation
uses baseunix,unix,math;
const
 Slayer : array[1..3] of string = ('Front','FrontPaste','FrontSilk');

  constructor Tgerber.create(filename : string);
  var
   x : integer;
  begin
  offx:=1e-3;
  offy:=10e-3;
  inherited create(filename);
  for x:=1 to 3 do with GL[x] do begin
   setlength(diams,0);
   assign(f,filestr+Slayer[x]+'.gbr');
   rewrite(f);
   assign(f2,filestr+Slayer[x]+'.gbr.tmp');
   rewrite(f2);
    writeln(f,'G04 Generated by DACAD*'); //G04 - ignore block  
    writeln(f,'G01*'); //linear interpolation, 1x scale
    //writeln(f,'G71*'); //milimeters
    writeln(f,'G90*'); //absolute format
    writeln(f,'%MOIN*%'); //milimeters
    writeln(f,'G04 Leading zero omitted, Abs format, 3.4 format*');
    writeln(f,'%FSLAX34Y34*%');
    writeln(f,'%LN',Slayer[x],'*%'); //Layer name
    writeln(f,'G04 APERTURE LIST*');
   end;
   with GL[0] do begin
     setlength(diams,0);
    assign(f,filestr+'.drl');
    rewrite(f);
    assign(f2,filestr+'.drl.tmp');
    rewrite(f2);
    writeln(f,'M48');
    writeln(f,';DRILL file {DACAD}');
//    writeln(f,';FORMAT={3:2 / absolute / millimeters / decimal format}');
//    writeln(f,'R,T');
//    writeln(f,'VER,1');
//    writeln(f,'FMAT,2');
//    writeln(f,'METRIC,TZ');
//    writeln(f,'TCST,OFF');
//    writeln(f,'ICI,OFF');
//    writeln(f,'ATC,ON');
     writeln(f,'METRIC');
    end;

 end;

procedure Tgerber.hole(r : tc;diam : double;nm : string);
var
d,l,x : integer;
xx,yy : double;
begin
d:=round(diam*1e3*1e6);
with GL[0] do begin
 l:=length(diams);
 x:=0;
 while (x<l) and (diams[x]<>d) do inc(x);
 if x=l then begin;
   setlength(diams,l+1);
   diams[x]:=d;
   writeln(f,'T',x+10,'C',d/1e4:0:3);
//  writeln(f,'T1C0.201');
   end;
   yy:=(r[2]+offy)*1e7;
   xx:=(r[1]+offx)*1e7;
    writeln(f2,'T',x+10);
    writeln(f2,'X',xx:0:0,'Y',YY:0:0);
//    writeln(f,'T1');
//    writeln(f,'X124.460Y119.380');
 end;
end;

procedure Tgerber.poly(n : integer;v : cvec;nm : string);
var
 l,x : integer;
 xx,yy : double;
begin
if layer=0 then l:=1 else if layer=1 then l:=2 else l:=3;
//writeln('Poly file ',l);
with GL[l] do begin
write(f2,'G36*');
for x:=0 to n-1 do begin
 yy:=(v[x,2]+offy)*1e7;
 xx:=(v[x,1]+offx)*1e7;
 write(f2,'X',xx:0:0,'Y',yy:0:0);
 if x=0 then writeln(f2,'D02*') else writeln(f2,'D01*');
//writeln(f2,'X39370Y11054D01*');
 end;
writeln(f2,'G37*');
end;
if layer=1 then begin
 layer:=0;
 poly(n,v,nm);
 layer:=1;
 end;
end;

procedure Tgerber.circle(r0 : tc;r : double;nm : string);
var
 l,x,d : integer;
 xx,yy : double;
begin
if layer=0 then l:=1 else if layer=2 then l:=2 else l:=3;
d:=round(r*2*1e3*1e4);
with GL[l] do begin
 l:=length(diams);
 x:=0;
 while (x<l) and (diams[x]<>d) do inc(x);
 if x=l then begin;
   setlength(diams,l+1);
   diams[x]:=d;
   writeln(f,'%ADD',x+10,'C,',d/1e4:0:4,'*%');
   end;
 yy:=(r0[2]+offy)*1e7;
 xx:=(r0[1]+offx)*1e7;
 writeln(f2,'G54D',x+10,'*X',xx:0:0,'Y',yy:0:0,'D03*');

 end;
end;

  procedure Tgerber.closedrw;
  var
   x : integer;
   s : string;
  begin
  for x:=1 to 3 do with GL[x] do begin
   writeln('Copy file',x);
   if length(diams)=0 then writeln(f,'%ADD10C,0.0100*%');
   writeln(f,'G04 APERTURE END LIST*');
   reset(f2);
   while not(eof(f2)) do begin
    readln(f2,s);
    writeln(f,s);
    end;
    writeln(f,'M02*');
    close(f);
    close(f2);
   end;
   with GL[0] do begin
    writeln(f,'%');
//    writeln(f,'M47');
//    writeln(f,'G05');
//    writeln(f,'M71');
    reset(f2);
   while not(eof(f2)) do begin
    readln(f2,s);
    writeln(f,s);
    end;
//    writeln(f,'T1');
//    writeln(f,'X124.460Y119.380');
//    writeln(f,'X114.300Y119.380');
//    writeln(f,'T0');
    writeln(f,'M30');
    close(f);
    close(f2);
   end;

  if doshow then show;
  end;

  procedure Tgerber.show;
  begin
//   shell('xfig -nosplash '+filestr+' &');
  end;
  

end.